starters:
  - name: Nexus GraphQL Shield
    path: /examples/with-graphql-nexus
  - name: GraphQL Shield Advanced
    path: /examples/advanced
  - name: GraphQL Shield Basic
    path: /examples/basic
  - name: Apollo Server Lambda GraphQL Shield
    path: /examples/with-apollo-server-lambda
  - name: GraphQL Shield with GraphQL Middleware Forward Binding
    path: /examples/with-graphql-middleware-forward-binding
